bf16: true
cutoff_len: 12000
dataset: Med_mimic_cxr_10000_cot_mllm_train_llm_only_F-I
dataset_dir: data
ddp_timeout: 180000000
deepspeed: cache/ds_z3_config.json
do_train: true
finetuning_type: full
flash_attn: fa2
gradient_accumulation_steps: 4
include_num_input_tokens_seen: true
learning_rate: 1.0e-05
logging_steps: 5
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: /data0/zhuoxu/yihong/code/LLaMA-Factory-main/saves/Qwen2-VL-7B-Instruct/full/train_Med_Qwen_2_VL_7B_Proj_stage1_warmup_only_F-I
num_train_epochs: 2.0
optim: adamw_torch
output_dir: saves/Qwen2-VL-7B-Instruct/full/train_Stage2_use_32B_MIMIC_CXR_10000_1_train_merger_llm_1e-5_epoch2
packing: false
per_device_train_batch_size: 2
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
template: qwen2_vl
trust_remote_code: true
warmup_steps: 0
